version: 0.2

phases:
  install:
    commands:
       - echo install phases
  pre_build:
    on-failure: ABORT | CONTINUE
    commands:
       - echo $CODEBUILD_INITIATOR
       - echo $CODEBUILD_BUILD_ID
       - echo $CODEBUILD_WEBHOOK_TRIGGER
       - echo $CODEBUILD_SOURCE_VERSION
       - pwd
       - sh ./builder/dev/dryrun/builder.sh ${CODEBUILD_BUILD_ID}